name: qr_maker
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  qr_flutter: ^4.1.0
  image_gallery_saver: ^2.0.2
  path_provider: ^2.0.15
  qr_code_scanner: ^1.0.1
  flutter_screenutil: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: Exo2
      fonts:
        - asset: assets/fonts/Exo2-Bold.ttf
          weight: 700
        - asset: assets/fonts/Exo2-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Exo2-Medium.ttf
          weight: 500
        - asset: assets/fonts/Exo2-Regular.ttf
          weight: 400
  uses-material-design: true
